version: "2"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:  --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - blackbox_exporter
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  blackbox_exporter:
    image: prom/blackbox-exporter:master
    container_name: blackbox_exporter
    command: --config.file=/config/blackbox.yml
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
