global:
  scrape_interval: 30s # By default, scrape targets every 15 seconds.

# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx_ip4]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://training-hs.tk # Target to probe with http on port 8080.
        - https://heliossolutions.co
        - https://www.cei.se
        - https://www.heliossolutions.in
        - https://www.amazon.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 54.161.186.15:9115  # The blackbox exporter's real hostname:port.
